### ISSUE TITLE
Item id's

### ISSUE THREAD

**Issue by cb12438** [stikosek/stikosekutilities#11]
How do i get item id's?

**Comment by cb12438** [comment]
Also found a bug when summoning mobs i cant killthem for some reason they take no damage

**Comment by cb12438** [comment]
Ima make a notepad of the item id's going threw the numbers then writing down what it drops

**Comment by stikosek** [comment]
Theese are known issues and will be fixed

**Comment by cb12438** [comment]
[Muck item id's.txt](https://github.com/stikosek/stikosekutilities/files/6681326/Muck.item.id.s.txt)
Thats all the id's if you wanna put that with the files :D took me like 3 hours but it was worth it also a possibility to spawn in power ups as well?

**Comment by mcamn21** [comment]
plz fix

**Comment by mcamn21** [comment]
also fix the invincible summons

**Comment by cb12438** [comment]
If its possible as well Please add the ability to kill players

**Comment by cb12438** [comment]
Suggegtions that i think should be added as well:
No clip
Teleport to a player
Kill a player with a button
TP to nearest pickup(drop)
Power up spawning

thats about it but i honestly do see some hope for this hack!

**Comment by stikosek** [comment]
Hi , in the new version you dont need item ids at all! Also No clip is added and most of the stuff you listed are planed
