### ISSUE TITLE
Can only open Settings and Credits.

### ISSUE THREAD

**Issue by uBreeze** [stikosek/stikosekutilities#12]
While it plays the click sfx and starts the game. The menu background has a group of players named Bean. However, I can not click Host or Join (or even Quit) and it won’t perform any actions.

I’m playing on Mac.

**Comment by stikosek** [comment]
What do you mean? I dont understand

**Comment by uBreeze** [comment]
I am completely stuck on the main menu, incapable of performing any actions whatsoever other than opening Settings.
