### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by NueWRld** [stikosek/stikosekutilities#17]
Upon loading in the files as shown in the post the game no longer starts correctly, the unity logo pops up and after a couple seconds the screen freezes and the proceeds to open up the unity crash handler and then crashes completely

**Comment by Critterthethird** [comment]
Yeah i had to get the old dll for the venlla version

**Comment by SneakyFlamingo** [comment]
This is probably because it hasnt updated to update 3 yet.

**Comment by Critterthethird** [comment]
Is he grounded?

**Comment by SneakyFlamingo** [comment]
wat

**Comment by stikosek** [comment]
Hi a new version was already posted on our discord server.
