### ISSUE TITLE
I'm not winning the achievements

### ISSUE THREAD

**Issue by nicothalianempire** [stikosek/stikosekutilities#21]
I'm not winning the achievements

**Comment by stikosek** [comment]
You sure? it might not show in game, make sure you check steam

**Comment by nicothalianempire** [comment]
i'm not earning the achievements!
you can fix an image here ?

**Comment by nicothalianempire** [comment]
![image](https://user-images.githubusercontent.com/86630549/124355009-6e552680-dbe5-11eb-9e4d-546e552792d0.png)
