### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by NAUT1VAL** [stikosek/stikosekutilities#22]
There was a bugfix and if i use the client and i play with friends they cant mine anything

**Comment by stikosek** [comment]
What version of su are you using?

**Comment by NAUT1VAL** [comment]
i use Muck version 1.26. Does it need to be injected thru an injector?

Op za 3 jul. 2021 09:36 schreef stikosek ***@***.***>:

**Comment by NAUT1VAL** [comment]
> What version of su are you using?

i was using the latest version. which was v.0.97

**Comment by FireMS** [comment]
I'm having the same issue, I can't do damage or break anything, I'm using the latest version.

**Comment by stikosek** [comment]
Old issue propably already fixed.
