### ISSUE TITLE
cant break or hit anything

### ISSUE THREAD

**Issue by LhymeFruit** [stikosek/stikosekutilities#24]
I cant break or hurt anything and also obombiam (however you spell it) is entirely missing

**Comment by FireMS** [comment]
Yeah, we're still waiting for a fix, hopefully, it'll be soon.

**Comment by McSkinnerOG** [comment]
Ive offered to fix the issues MULTIPLE times but the dev seems to not give a shit and only cares about his code being "not stolen" despite the fact ive been sending him fixes and new features.

**Comment by stikosek** [comment]
> Ive offered to fix the issues MULTIPLE times but the dev seems to not give a shit and only cares about his code being "not stolen" despite the fact ive been sending him fixes and new features.

I have no idea who are you
