### ISSUE TITLE
Unity Crash Handler

### ISSUE THREAD

**Issue by FireMS** [stikosek/stikosekutilities#25]
The game will crash on startup due to Unity Crash Handler, if you could fix this soon we would really appreciate it.

**Comment by Hydrolythical** [comment]
dude you should join the discord server theres new versions uploading in there

**Comment by FireMS** [comment]
Alright, thanks for telling me mate

**Comment by Volester** [comment]
Whats the discord server ;-;

**Comment by Epikest** [comment]
> 
> Whats the discord server ;-;

discord.gg/stikosek
