### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by ItsZify** [stikosek/stikosekutilities#8]
add like an openable menu to toggle all hacks and set key-binds and to also be able to spawn every item :)

**Comment by cb12438** [comment]
If the creator wants he can use this right here as a example i already suggested this he said no it would be to hard to code

https://github.com/win32kbase/MuckInternal

**Comment by stikosek** [comment]
I am making my new gui system for the hackclient and it will be added in stikosekutilitiesV0.9 :)

**Comment by cb12438** [comment]
Sweet can you make it where you can spawn mobs as well?

**Comment by stikosek** [comment]
A new version is out and all the stuff you wanted is added! :D i am now closing this issue :) 👍
